version: '3.8'

services:
 db:
  build:
   context: ./docker/postgres
   dockerfile: Dockerfile
  environment:
   - POSTGRES_PASSWORD=admin
  volumes:
   - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


 drf:
  build:
   context: ./
   dockerfile: Dockerfile
  volumes:
   - ./:/usr/src/app
  depends_on:
   - db
  ports:
   - "8000:8000"
   
 nginx:
  build:
   context: ./docker/nginx
   dockerfile: Dockerfile
  depends_on:
   - db
   - drf
  ports:
   - "80:80"
  volumes:
   - ./static/:/static
